NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /

api:
    # loads routes from the YAML or XML files found in some bundle directory
    resource: '../src/Api/Resources/routing/'
    type:     directory

authorization:
    resource: '../src/Authorization/Controller/'
    type: annotation
